version: '3'
services:
  django:
    build:
      context: .
      dockerfile: ./docker/django/Dockerfile
    platform: linux/amd64
    command: gunicorn backend.wsgi:application --bind 0.0.0.0:8000
    volumes:
      - .:/code
    expose:
      - "8000"
    restart: "on-failure"
  nginx:
    build: ./docker/nginx
    platform: linux/amd64
    ports:
      - "80:80"
    volumes:
      - .:/code
    depends_on:
      - django
    restart: "on-failure"
