version: '3'
services:
  nginx:
    image: nginx:latest
    ports:
      - "80:80"
    volumes:
      - .:/code
      - ./docker/nginx:/etc/nginx.conf.d
    depends_on:
      - django
  django:
    build:
      context: .
      dockerfile: ./docker/django/Dockerfile
    command: gunicorn backend.wsgi:application --bind 0.0.0.0:8000
    # command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/code
    expose:
      - "8000"
    # ports:
      # - "8000:8000"