# Generated by Django 3.2.6 on 2021-08-14 00:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Site',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('_id', models.CharField(max_length=32, unique=True)),
                ('name', models.CharField(max_length=256)),
                ('LAeq', models.CharField(max_length=256)),
                ('LCeq_Aeq', models.FloatField()),
                ('GreenRatio', models.FloatField()),
                ('NumOfPeople', models.IntegerField()),
                ('NumOfVehicles', models.IntegerField()),
                ('Loudness', models.IntegerField()),
                ('media_url', models.URLField()),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('_id', models.CharField(max_length=32, unique=True)),
                ('name', models.CharField(max_length=256)),
                ('pw_hash', models.CharField(max_length=64)),
            ],
        ),
    ]
