# Generated by Django 3.2.6 on 2021-08-24 19:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('basic', '0002_auto_20210818_1906'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='notification_agreement',
            field=models.BooleanField(default=True),
        ),
    ]
