# Generated by Django 3.2.6 on 2021-09-07 10:24

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('basic', '0005_image_video'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='date_uploaded',
            field=models.DateTimeField(default=datetime.datetime(2021, 9, 7, 10, 24, 5, 596650)),
        ),
        migrations.AlterField(
            model_name='video',
            name='date_uploaded',
            field=models.DateTimeField(default=datetime.datetime(2021, 9, 7, 10, 24, 5, 596889)),
        ),
    ]
