# Generated by Django 3.2.6 on 2021-12-03 11:20

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('basic', '0006_auto_20210907_1024'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='date_uploaded',
            field=models.DateTimeField(default=datetime.datetime(2021, 12, 3, 11, 20, 9, 381046)),
        ),
        migrations.AlterField(
            model_name='video',
            name='date_uploaded',
            field=models.DateTimeField(default=datetime.datetime(2021, 12, 3, 11, 20, 9, 381280)),
        ),
    ]
