# Generated by Django 3.2.6 on 2021-12-03 11:47

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('basic', '0007_auto_20211203_1120'),
    ]

    operations = [
        migrations.AddField(
            model_name='video',
            name='created_datetime',
            field=models.DateTimeField(auto_now_add=True, null=True, verbose_name='생성일시'),
        ),
        migrations.AddField(
            model_name='video',
            name='loudness',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='video',
            name='revisitation',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='video',
            name='updated_datetime',
            field=models.DateTimeField(auto_now=True, null=True, verbose_name='수정일시'),
        ),
        migrations.AlterField(
            model_name='image',
            name='date_uploaded',
            field=models.DateTimeField(default=datetime.datetime(2021, 12, 3, 11, 47, 53, 855549)),
        ),
        migrations.AlterField(
            model_name='video',
            name='date_uploaded',
            field=models.DateTimeField(default=datetime.datetime(2021, 12, 3, 11, 47, 53, 855772)),
        ),
        migrations.AlterField(
            model_name='video',
            name='title',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
