# Generated by Django 3.2.6 on 2021-12-03 12:08

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('basic', '0008_auto_20211203_1147'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='video',
            name='date_uploaded',
        ),
        migrations.RemoveField(
            model_name='video',
            name='id',
        ),
        migrations.RemoveField(
            model_name='video',
            name='title',
        ),
        migrations.AddField(
            model_name='video',
            name='json',
            field=models.TextField(default=None, null=True),
        ),
        migrations.AddField(
            model_name='video',
            name='prediction',
            field=models.FloatField(default=None, null=True),
        ),
        migrations.AddField(
            model_name='video',
            name='status',
            field=models.CharField(default='ready', max_length=30),
        ),
        migrations.AddField(
            model_name='video',
            name='video_id',
            field=models.AutoField(default=0, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='image',
            name='date_uploaded',
            field=models.DateTimeField(default=datetime.datetime(2021, 12, 3, 12, 8, 38, 286198)),
        ),
    ]
