# Generated by Django 3.2.6 on 2021-12-03 12:09

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('basic', '0009_auto_20211203_1208'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='date_uploaded',
            field=models.DateTimeField(default=datetime.datetime(2021, 12, 3, 12, 8, 59, 628473)),
        ),
        migrations.AlterField(
            model_name='video',
            name='video_id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
