# Generated by Django 3.2.6 on 2021-12-03 12:10

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('basic', '0010_auto_20211203_1209'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='date_uploaded',
            field=models.DateTimeField(default=datetime.datetime(2021, 12, 3, 12, 10, 45, 634333)),
        ),
        migrations.AlterField(
            model_name='video',
            name='video_id',
            field=models.AutoField(db_index=True, primary_key=True, serialize=False),
        ),
    ]
