# Generated by Django 3.2.6 on 2021-12-03 12:11

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('basic', '0011_auto_20211203_1210'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='date_uploaded',
            field=models.DateTimeField(default=datetime.datetime(2021, 12, 3, 12, 11, 7, 295590)),
        ),
    ]
