# Generated by Django 3.2.6 on 2021-12-03 12:13

import datetime
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('basic', '0012_alter_image_date_uploaded'),
    ]

    operations = [
        migrations.CreateModel(
            name='VideoResult',
            fields=[
                ('created_datetime', models.DateTimeField(auto_now_add=True, null=True, verbose_name='생성일시')),
                ('updated_datetime', models.DateTimeField(auto_now=True, null=True, verbose_name='수정일시')),
                ('video_id', models.AutoField(db_index=True, primary_key=True, serialize=False)),
                ('video', models.FileField(null=True, upload_to='videos/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['MOV', 'avi', 'mp4', 'webm', 'mkv'])])),
                ('loudness', models.FloatField(blank=True, null=True)),
                ('revisitation', models.FloatField(blank=True, null=True)),
                ('status', models.CharField(default='ready', max_length=30)),
                ('json', models.TextField(default=None, null=True)),
                ('prediction', models.FloatField(default=None, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.DeleteModel(
            name='Video',
        ),
        migrations.AlterField(
            model_name='image',
            name='date_uploaded',
            field=models.DateTimeField(default=datetime.datetime(2021, 12, 3, 12, 13, 1, 178029)),
        ),
    ]
