# Generated by Django 3.2.6 on 2021-08-18 19:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('basic', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SiteAnalysis',
            fields=[
                ('id', models.BigAutoField(help_text='SiteAnalysis ID', primary_key=True, serialize=False)),
                ('l_aeq', models.FloatField()),
                ('l_ceq', models.FloatField()),
                ('green_ratio', models.FloatField()),
                ('grey_ratio', models.FloatField()),
                ('sky_ratio', models.FloatField()),
                ('people_count', models.IntegerField()),
                ('vehicle_count', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='SiteSurvey',
            fields=[
                ('id', models.BigAutoField(help_text='Site Survey ID', primary_key=True, serialize=False)),
                ('loudness', models.FloatField(help_text='Loudness')),
                ('revisitation', models.FloatField(help_text='Revisitation')),
            ],
        ),
        migrations.CreateModel(
            name='TCI_RS',
            fields=[
                ('id', models.BigAutoField(help_text='TCI RS ID', primary_key=True, serialize=False)),
                ('harm_avoidance', models.CharField(help_text='Harm Avoidance', max_length=64, null=True)),
                ('reward_dependence', models.CharField(help_text='Reward Dependence', max_length=64, null=True)),
                ('self_directedness', models.CharField(help_text='Self Directedness', max_length=64, null=True)),
                ('cooperativeness', models.CharField(help_text='Cooperativeness', max_length=64, null=True)),
                ('self_transcendence', models.CharField(help_text='Self Transcendence', max_length=64, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='UserSurvey',
            fields=[
                ('id', models.BigAutoField(help_text='User Survey ID', primary_key=True, serialize=False)),
            ],
        ),
        migrations.RemoveField(
            model_name='site',
            name='GreenRatio',
        ),
        migrations.RemoveField(
            model_name='site',
            name='LAeq',
        ),
        migrations.RemoveField(
            model_name='site',
            name='LCeq_Aeq',
        ),
        migrations.RemoveField(
            model_name='site',
            name='Loudness',
        ),
        migrations.RemoveField(
            model_name='site',
            name='NumOfPeople',
        ),
        migrations.RemoveField(
            model_name='site',
            name='NumOfVehicles',
        ),
        migrations.RemoveField(
            model_name='site',
            name='_id',
        ),
        migrations.RemoveField(
            model_name='user',
            name='_id',
        ),
        migrations.AddField(
            model_name='user',
            name='age',
            field=models.IntegerField(help_text='Age', null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='gender',
            field=models.CharField(help_text='Gender', max_length=32, null=True),
        ),
        migrations.AlterField(
            model_name='site',
            name='id',
            field=models.BigAutoField(help_text='Site ID', primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='user',
            name='id',
            field=models.BigAutoField(help_text='User ID', primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='user',
            name='name',
            field=models.CharField(help_text='Name', max_length=256, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='pw_hash',
            field=models.CharField(help_text='PW Hash', max_length=64, null=True),
        ),
        migrations.CreateModel(
            name='Prediction',
            fields=[
                ('id', models.BigAutoField(help_text='Prediction ID', primary_key=True, serialize=False)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('value', models.FloatField()),
                ('site_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='basic.site')),
                ('site_survey_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='basic.sitesurvey')),
                ('user_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='basic.user')),
            ],
        ),
        migrations.AddField(
            model_name='site',
            name='site_analysis_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='basic.siteanalysis'),
        ),
        migrations.AddField(
            model_name='user',
            name='tci_rs_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='basic.tci_rs'),
        ),
        migrations.AddField(
            model_name='user',
            name='user_survey_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='basic.usersurvey'),
        ),
    ]
