# Generated by Django 3.2.6 on 2021-12-03 13:46

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('basic', '0002_auto_20211203_1231'),
    ]

    operations = [
        migrations.RenameField(
            model_name='videoresult',
            old_name='json',
            new_name='json_data',
        ),
        migrations.AlterField(
            model_name='image',
            name='date_uploaded',
            field=models.DateTimeField(default=datetime.datetime(2021, 12, 3, 13, 46, 29, 562028)),
        ),
    ]
