# Generated by Django 3.2.6 on 2021-12-09 11:54

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('basic', '0003_auto_20211203_1346'),
    ]

    operations = [
        migrations.AddField(
            model_name='videoresult',
            name='uploaded_by',
            field=models.CharField(default='', max_length=64, null=True),
        ),
        migrations.AlterField(
            model_name='image',
            name='date_uploaded',
            field=models.DateTimeField(default=datetime.datetime(2021, 12, 9, 11, 54, 32, 716389)),
        ),
    ]
